# **Laboratorio 8: Ready, Set, Deploy! 👩‍🚀👨‍🚀**

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>

### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Naomi Cautivo B.
- Nombre de alumno 2: Máximo Flores Valenzuela

### **Link de repositorio de GitHub:** [Repositorio](https://github.com/maxfloresv/MDS7202/)

## Temas a tratar

- Entrenamiento y registro de modelos usando MLFlow.
- Despliegue de modelo usando FastAPI
- Containerización del proyecto usando Docker

## Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.

### Objetivos principales del laboratorio

- Generar una solución a un problema a partir de ML
- Desplegar su solución usando MLFlow, FastAPI y Docker

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre DataFrames.

# **Introducción**

<p align="center">
  <img src="https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExODJnMHJzNzlkNmQweXoyY3ltbnZ2ZDlxY2c0aW5jcHNzeDNtOXBsdCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/AbPdhwsMgjMjax5reo/giphy.gif" width="400">
</p>



Consumida en la tristeza el despido de Renacín, Smapina ha decaído en su desempeño, lo que se ha traducido en un irregular tratamiento del agua. Esto ha implicado una baja en la calidad del agua, llegando a haber algunos puntos de la comuna en la que el vital elemento no es apto para el consumo humano. Es por esto que la sanitaria pública de la municipalidad de Maipú se ha contactado con ustedes para que le entreguen una urgente solución a este problema (a la vez que dejan a Smapina, al igual que Renacín, sin trabajo 😔).

El problema que la empresa le ha solicitado resolver es el de elaborar un sistema que les permita saber si el agua es potable o no. Para esto, la sanitaria les ha proveido una base de datos con la lectura de múltiples sensores IOT colocados en diversas cañerías, conductos y estanques. Estos sensores señalan nueve tipos de mediciones químicas y más una etiqueta elaborada en laboratorio que indica si el agua es potable o no el agua.

La idea final es que puedan, en el caso que el agua no sea potable, dar un aviso inmediato para corregir el problema. Tenga en cuenta que parte del equipo docente vive en Maipú y su intoxicación podría implicar graves problemas para el cierre del curso.

Atributos:

1. pH value: pH del agua.
2. Hardness: Capacidad de precipitar jabón en mg/L.
3. Solids (Total dissolved solids - TDS): Cantidad de sólidos disueltos en ppm.
4. Chloramines: Cantidad de cloraminas en ppm.
5. Sulfate: Cantidad de sulfatos disueltos en ppm.
6. Conductivity: Conductividad eléctrica del agua en μS/cm.
7. Organic_carbon: Cantidad de carbono orgánico en ppm.
8. Trihalomethanes: Cantidad de trihalometanos en μg/L
9. Turbidity: Medida de turbidez del agua en NTU.


Unidades de medida:

1. PPM: Partes por millón, en agua equivale a que 1 ppm es una unidad de sustancia por cada millón de agua (es decir, si tengo 5 millones de partículas de agua, tendré 5 de esa sustancia a 1ppm.)
2. mg/L: Miligramos por litro.
3. μS/cm: Microsiemens por centímetro (unidad de conductividad eléctrica.)
4. μg/L: Microgramos por litro.
5. NTU: Unidad nefelométrica de turbidez.


Variable a predecir:

10. Potability (1 si es potable, 0 no potable)

Descripción de cada atributo se pueden encontrar en el siguiente link: [dataset](https://www.kaggle.com/adityakadiwal/water-potability)

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
water_data = pd.read_csv("water_potability.csv")

In [4]:
water_data.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,2785.000000,3276.000000,3276.000000,3276.000000,2495.000000,3276.000000,3276.000000,3114.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.594320,32.879761,8768.570828,1.583085,41.416840,80.824064,3.308162,16.175008,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.093092,176.850538,15666.690297,6.127421,307.699498,365.734414,12.065801,55.844536,3.439711,0.000000
50%,7.036752,196.967627,20927.833607,7.130299,333.073546,421.884968,14.218338,66.622485,3.955028,0.000000
75%,8.062066,216.667456,27332.762127,8.114887,359.950170,481.792304,16.557652,77.337473,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [5]:
water_data.dtypes

ph                 float64
Hardness           float64
Solids             float64
Chloramines        float64
Sulfate            float64
Conductivity       float64
Organic_carbon     float64
Trihalomethanes    float64
Turbidity          float64
Potability           int64
dtype: object

In [6]:
water_data.isna().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [8]:
water_data.shape

(3276, 10)

In [9]:
water_data.fillna(water_data.mean(), inplace=True)

In [10]:
water_data.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
count,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000,3276.000000
mean,7.080795,196.369496,22014.092526,7.122277,333.775777,426.205111,14.284970,66.396293,3.966786,0.390110
std,1.469956,32.879761,8768.570828,1.583085,36.142612,80.824064,3.308162,15.769881,0.780382,0.487849
min,0.000000,47.432000,320.942611,0.352000,129.000000,181.483754,2.200000,0.738000,1.450000,0.000000
25%,6.277673,176.850538,15666.690297,6.127421,317.094638,365.734414,12.065801,56.647656,3.439711,0.000000
50%,7.080795,196.967627,20927.833607,7.130299,333.775777,421.884968,14.218338,66.396293,3.955028,0.000000
75%,7.870050,216.667456,27332.762127,8.114887,350.385756,481.792304,16.557652,76.666609,4.500320,1.000000
max,14.000000,323.124000,61227.196008,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000,1.000000

In [11]:
X=water_data.drop("Potability", axis=1)
y=water_data["Potability"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# **1. Optimización de modelos con Optuna + MLFlow (2.0 puntos)**

El objetivo de esta sección es que ustedes puedan combinar Optuna con MLFlow para poder realizar la optimización de los hiperparámetros de sus modelos.

Como aún no hemos hablado nada sobre `MLFlow` cabe preguntarse: **¡¿Qué !"#@ es `MLflow`?!**

<p align="center">
  <img src="https://media.tenor.com/eusgDKT4smQAAAAC/matthew-perry-chandler-bing.gif" width="400">
</p>

## **MLFlow**

`MLflow` es una plataforma de código abierto que simplifica la gestión y seguimiento de proyectos de aprendizaje automático. Con sus herramientas, los desarrolladores pueden organizar, rastrear y comparar experimentos, además de registrar modelos y controlar versiones.

<p align="center">
  <img src="https://spark.apache.org/images/mlflow-logo.png" width="350">
</p>

Si bien esta plataforma cuenta con un gran número de herramientas y funcionalidades, en este laboratorio trabajaremos con dos:
1. **Runs**: Registro que constituye la información guardada tras la ejecución de un entrenamiento. Cada `run` tiene su propio run_id, el cual sirve como identificador para el entrenamiento en sí mismo. Dentro de cada `run` podremos acceder a información como los hiperparámetros utilizados, las métricas obtenidas, las librerías requeridas y hasta nos permite descargar el modelo entrenado.
2. **Experiments**: Se utilizan para agrupar y organizar diferentes ejecuciones de modelos (`runs`). En ese sentido, un experimento puede agrupar 1 o más `runs`. De esta manera, es posible también registrar métricas, parámetros y archivos (artefactos) asociados a cada experimento.

### **Todo bien pero entonces, ¿cómo se usa en la práctica `MLflow`?**

Es sencillo! Considerando un problema de machine learning genérico, podemos registrar la información relevante del entrenamiento ejecutando `mlflow.autolog()` antes entrenar nuestro modelo. Veamos este bonito ejemplo facilitado por los mismos creadores de `MLflow`:

```python
#!pip install mlflow
import mlflow # importar mlflow

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.ensemble import RandomForestRegressor

db = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(db.data, db.target)

# Create and train models.
rf = RandomForestRegressor(n_estimators=100, max_depth=6, max_features=3)

mlflow.autolog() # registrar automáticamente información del entrenamiento
with mlflow.start_run(): # delimita inicio y fin del run
    # aquí comienza el run
    rf.fit(X_train, y_train) # train the model
    predictions = rf.predict(X_test) # Use the model to make predictions on the test dataset.
    # aquí termina el run
```

Si ustedes ejecutan el código anterior en sus máquinas locales (desde un jupyter notebook por ejemplo) se darán cuenta que en su directorio *root* se ha creado la carpeta `mlruns`. Esta carpeta lleva el tracking de todos los entrenamientos ejecutados desde el directorio root (importante: si se cambian de directorio y vuelven a ejecutar el código anterior, se creará otra carpeta y no tendrán acceso al entrenamiento anterior). Para visualizar estos entrenamientos, `MLflow` nos facilita hermosa interfaz visual a la que podemos acceder ejecutando:

```
mlflow ui
```

y luego pinchando en la ruta http://127.0.0.1:5000 que nos retorna la terminal. Veamos en vivo algunas de sus funcionalidades!

<p align="center">
  <img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZXVuM3A5MW1heDFpa21qbGlwN2pyc2VoNnZsMmRzODZxdnluemo2bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o84sq21TxDH6PyYms/giphy.gif" width="400">
</p>

Les dejamos también algunos comandos útiles:

- `mlflow.create_experiment("nombre_experimento")`: Les permite crear un nuevo experimento para agrupar entrenamientos
- `mlflow.log_metric("nombre_métrica", métrica)`: Les permite registrar una métrica *custom* bajo el nombre de "nombre_métrica"

## **1.1 Combinando Optuna + MLflow (2.0 puntos)**

Ahora que tenemos conocimiento de ambas herramientas, intentemos ahora combinarlas para **más sabor**. El objetivo de este apartado es simple: automatizar la optimización de los parámetros de nuestros modelos usando `Optuna` y registrando de forma automática cada resultado en `MLFlow`.

Considerando el objetivo planteado, se le pide completar la función `optimize_model`, la cual debe:
- **Optimizar los hiperparámetros del modelo `XGBoost` usando `Optuna`.**
- **Registrar cada entrenamiento en un experimento nuevo**, asegurándose de que la métrica `f1-score` se registre como `"valid_f1"`. No se deben guardar todos los experimentos en *Default*; en su lugar, cada `experiment` y `run` deben tener nombres interpretables, reconocibles y diferentes a los nombres por defecto (por ejemplo, para un run: "XGBoost con lr 0.1").
- **Guardar los gráficos de Optuna** dentro de una carpeta de artefactos de Mlflow llamada `/plots`.
- **Devolver el mejor modelo** usando la función `get_best_model` y serializarlo en el disco con `pickle.dump`. Luego, guardar el modelo en la carpeta `/models`.
- **Guardar el código en `optimize.py`**. La ejecución de `python optimize.py` debería ejecutar la función `optimize_model`.
- **Guardar las versiones de las librerías utilizadas** en el desarrollo.
- **Respalde las configuraciones del modelo final y la importancia de las variables** en un gráfico dentro de la carpeta `/plots` creada anteriormente.

*Hint: Le puede ser útil revisar los parámetros que recibe `mlflow.start_run`*

```python
def get_best_model(experiment_id):
    runs = mlflow.search_runs(experiment_id)
    best_model_id = runs.sort_values("metrics.valid_f1")["run_id"].iloc[0]
    best_model = mlflow.sklearn.load_model("runs:/" + best_model_id + "/model")

    return best_model
```

In [15]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-3.5.0-py3-none-any.whl.metadata (30 kB)
Collecting mlflow-skinny==3.5.0 (from mlflow)
  Downloading mlflow_skinny-3.5.0-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-tracing==3.5.0 (from mlflow)
  Downloading mlflow_tracing-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: Flask-CORS<7 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (6.0.1)
Requirement already satisfied: Flask<4 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (1.16.5)
Collecting cryptography<47,>=43.0.0 (from mlflow)
  Downloading cryptography-46.0.3-cp38-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting fastmcp<3,>=2.0.0 (from mlflow)
  Downloading fastmcp-2.12.5-py3-none-any.whl.metadata (19 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: matplotlib<4 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (3.10.6)
Requirement already satisfied: numpy<3 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (2.1.4)
Requirement already satisfied: pyarrow<22,>=4.0.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (21.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (1.4.2)
Requirement already satisfied: scipy<2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (1.11.4)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow) (2.0.43)
Collecting waitress<4 (from mlflow)
  Downloading waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting cachetools<7,>=5.0.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading cachetools-6.2.1-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (8.2.1)
Requirement already satisfied: cloudpickle<4 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (3.1.1)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading databricks_sdk-0.69.0-py3-none-any.whl.metadata (39 kB)
Collecting fastapi<1 (from mlflow-skinny==3.5.0->mlflow)
  Downloading fastapi-0.119.1-py3-none-any.whl.metadata (28 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.5.0->mlflow)
  Downloading gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (8.7.0)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading opentelemetry_api-1.38.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading opentelemetry_proto-1.38.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading opentelemetry_sdk-1.38.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: packaging<26 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (25.0)
Collecting protobuf<7,>=3.12.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading protobuf-6.33.0-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pydantic<3,>=1.10.8 (from mlflow-skinny==3.5.0->mlflow)
  Downloading pydantic-2.12.3-py3-none-any.whl.metadata (87 kB)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.5.0->mlflow)
  Using cached python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.5.0->mlflow)
  Downloading sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mlflow-skinny==3.5.0->mlflow) (4.15.0)
Collecting uvicorn<1 (from mlflow-skinny==3.5.0->mlflow)
  Downloading uvicorn-0.38.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: Mako in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: tomli in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (2.2.1)
Requirement already satisfied: colorama in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.5.0->mlflow) (0.4.6)
Collecting cffi>=2.0.0 (from cryptography<47,>=43.0.0->mlflow)
  Downloading cffi-2.0.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.5.0->mlflow)
  Downloading google_auth-2.41.1-py2.py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: pywin32>=304 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Collecting starlette<0.49.0,>=0.40.0 (from fastapi<1->mlflow-skinny==3.5.0->mlflow)
  Downloading starlette-0.48.0-py3-none-any.whl.metadata (6.3 kB)
Collecting authlib>=1.5.2 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading authlib-1.6.5-py2.py3-none-any.whl.metadata (9.8 kB)
Collecting cyclopts>=3.0.0 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading cyclopts-4.0.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: exceptiongroup>=1.2.2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from fastmcp<3,>=2.0.0->mlflow) (1.3.0)
Collecting httpx>=0.28.1 (from fastmcp<3,>=2.0.0->mlflow)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting mcp<1.17.0,>=1.12.4 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading mcp-1.16.0-py3-none-any.whl.metadata (80 kB)
Collecting openapi-core>=0.19.5 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading openapi_core-0.19.5-py3-none-any.whl.metadata (6.6 kB)
Collecting openapi-pydantic>=0.5.1 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading openapi_pydantic-0.5.1-py3-none-any.whl.metadata (10 kB)
Collecting pyperclip>=1.9.0 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading pyperclip-1.11.0-py3-none-any.whl.metadata (2.4 kB)
Collecting rich>=13.9.4 (from fastmcp<3,>=2.0.0->mlflow)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from Flask<4->mlflow) (3.0.6)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.5.0->mlflow)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.5.0->mlflow)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.5.0->mlflow)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.5.0->mlflow)
  Using cached rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.6-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.5.0->mlflow) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from matplotlib<4->mlflow) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from matplotlib<4->mlflow) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from matplotlib<4->mlflow) (3.2.0)
Collecting anyio>=4.5 (from mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow)
  Downloading anyio-4.11.0-py3-none-any.whl.metadata (4.1 kB)
Collecting httpx-sse>=0.4 (from mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: jsonschema>=4.20.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow) (4.25.0)
Collecting pydantic-settings>=2.5.2 (from mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow)
  Downloading pydantic_settings-2.11.0-py3-none-any.whl.metadata (3.4 kB)
Collecting python-multipart>=0.0.9 (from mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow)
  Using cached python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Collecting sse-starlette>=1.6.1 (from mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow)
  Downloading sse_starlette-3.0.2-py3-none-any.whl.metadata (11 kB)
Collecting opentelemetry-semantic-conventions==0.59b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.5.0->mlflow)
  Downloading opentelemetry_semantic_conventions-0.59b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from pandas<3->mlflow) (2025.2)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=1.10.8->mlflow-skinny==3.5.0->mlflow)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.4 (from pydantic<3,>=1.10.8->mlflow-skinny==3.5.0->mlflow)
  Downloading pydantic_core-2.41.4-cp310-cp310-win_amd64.whl.metadata (7.4 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=1.10.8->mlflow-skinny==3.5.0->mlflow)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: six>=1.5 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.5.0->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.5.0->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.5.0->mlflow) (2025.8.3)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.5.0->mlflow)
  Using cached pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: joblib>=1.2.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from scikit-learn<2->mlflow) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: greenlet>=1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.2.4)
Collecting sniffio>=1.1 (from anyio>=4.5->mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11>=0.8 (from uvicorn<1->mlflow-skinny==3.5.0->mlflow)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: pycparser in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow) (2.23)
Requirement already satisfied: attrs>=23.1.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from cyclopts>=3.0.0->fastmcp<3,>=2.0.0->mlflow) (24.3.0)
Collecting docstring-parser<4.0,>=0.15 (from cyclopts>=3.0.0->fastmcp<3,>=2.0.0->mlflow)
  Downloading docstring_parser-0.17.0-py3-none-any.whl.metadata (3.5 kB)
Collecting rich-rst<2.0.0,>=1.3.1 (from cyclopts>=3.0.0->fastmcp<3,>=2.0.0->mlflow)
  Downloading rich_rst-1.3.2-py3-none-any.whl.metadata (6.1 kB)
Collecting docutils (from rich-rst<2.0.0,>=1.3.1->cyclopts>=3.0.0->fastmcp<3,>=2.0.0->mlflow)
  Downloading docutils-0.22.2-py3-none-any.whl.metadata (15 kB)
Collecting httpcore==1.* (from httpx>=0.28.1->fastmcp<3,>=2.0.0->mlflow)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (3.0.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from jsonschema>=4.20.0->mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from jsonschema>=4.20.0->mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from jsonschema>=4.20.0->mcp<1.17.0,>=1.12.4->fastmcp<3,>=2.0.0->mlflow) (0.22.3)
Collecting isodate (from openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Collecting jsonschema-path<0.4.0,>=0.3.1 (from openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading jsonschema_path-0.3.4-py3-none-any.whl.metadata (4.3 kB)
Collecting more-itertools (from openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading more_itertools-10.8.0-py3-none-any.whl.metadata (39 kB)
Collecting openapi-schema-validator<0.7.0,>=0.6.0 (from openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading openapi_schema_validator-0.6.3-py3-none-any.whl.metadata (5.4 kB)
Collecting openapi-spec-validator<0.8.0,>=0.7.1 (from openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading openapi_spec_validator-0.7.2-py3-none-any.whl.metadata (5.7 kB)
Collecting parse (from openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading parse-1.20.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting pathable<0.5.0,>=0.4.1 (from jsonschema-path<0.4.0,>=0.3.1->openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading pathable-0.4.4-py3-none-any.whl.metadata (1.8 kB)
Collecting rfc3339-validator (from openapi-schema-validator<0.7.0,>=0.6.0->openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting lazy-object-proxy<2.0.0,>=1.7.1 (from openapi-spec-validator<0.8.0,>=0.7.1->openapi-core>=0.19.5->fastmcp<3,>=2.0.0->mlflow)
  Downloading lazy_object_proxy-1.12.0-cp310-cp310-win_amd64.whl.metadata (5.3 kB)
Collecting email-validator>=2.0.0 (from pydantic[email]>=2.11.7->fastmcp<3,>=2.0.0->mlflow)
  Using cached email_validator-2.3.0-py3-none-any.whl.metadata (26 kB)
Collecting dnspython>=2.0.0 (from email-validator>=2.0.0->pydantic[email]>=2.11.7->fastmcp<3,>=2.0.0->mlflow)
  Using cached dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.9.4->fastmcp<3,>=2.0.0->mlflow)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\naoca\.conda\envs\mds7202_b\lib\site-packages (from rich>=13.9.4->fastmcp<3,>=2.0.0->mlflow) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.9.4->fastmcp<3,>=2.0.0->mlflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading mlflow-3.5.0-py3-none-any.whl (8.8 MB)
   ---------------------------------------- 0.0/8.8 MB ? eta -:--:--
   ------------------------- -------------- 5.5/8.8 MB 41.9 MB/s eta 0:00:01
   ---------------------------------------- 8.8/8.8 MB 25.9 MB/s  0:00:00
Downloading mlflow_skinny-3.5.0-py3-none-any.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 43.6 MB/s  0:00:00
Downloading mlflow_tracing-3.5.0-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 1.3/1.3 MB 32.6 MB/s  0:00:00
Downloading cachetools-6.2.1-py3-none-any.whl (11 kB)
Downloading cryptography-46.0.3-cp38-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ---------------------------------------- 3.5/3.5 MB 29.5 MB/s  0:00:00
Downloading databricks_sdk-0.69.0-py3-none-any.whl (749 kB)
   ---------------------------------------- 0.0/749.8 kB ? eta -:--:--
   ---------------------------------------- 749.8/749.8 kB 30.5 MB/s  0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
Downloading fastapi-0.119.1-py3-none-any.whl (108 kB)
Downloading fastmcp-2.12.5-py3-none-any.whl (329 kB)
Downloading gitpython-3.1.45-py3-none-any.whl (208 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading google_auth-2.41.1-py2.py3-none-any.whl (221 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.6-py3-none-any.whl (203 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading mcp-1.16.0-py3-none-any.whl (167 kB)
Downloading opentelemetry_api-1.38.0-py3-none-any.whl (65 kB)
Downloading opentelemetry_proto-1.38.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.38.0-py3-none-any.whl (132 kB)
Downloading opentelemetry_semantic_conventions-0.59b0-py3-none-any.whl (207 kB)
Downloading protobuf-6.33.0-cp310-abi3-win_amd64.whl (436 kB)
Downloading pydantic-2.12.3-py3-none-any.whl (462 kB)
Downloading pydantic_core-2.41.4-cp310-cp310-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 28.0 MB/s  0:00:00
Using cached python_dotenv-1.1.1-py3-none-any.whl (20 kB)
Using cached rsa-4.9.1-py3-none-any.whl (34 kB)
Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
Downloading starlette-0.48.0-py3-none-any.whl (73 kB)
Downloading anyio-4.11.0-py3-none-any.whl (109 kB)
Downloading uvicorn-0.38.0-py3-none-any.whl (68 kB)

In [35]:
import xgboost as xgb
from xgboost import XGBClassifier
import mlflow
import mlflow.xgboost
from sklearn.metrics import f1_score
import xgboost
import optuna
import sklearn
import matplotlib
import os

In [27]:
def get_best_model(experiment_id):
    runs = mlflow.search_runs(experiment_id)
    best_model_id = runs.sort_values("metrics.valid_f1")["run_id"].iloc[0]
    best_model = mlflow.sklearn.load_model("runs:/" + best_model_id + "/model")

    return best_model

In [33]:
def optimize_model():
  experiment_name = "Water_Potability_Optimization"
  experiment=mlflow.get_experiment_by_name(experiment_name)
  if experiment is None:
      experiment_id = mlflow.create_experiment(experiment_name)
  else:
      experiment_id = mlflow.get_experiment_by_name(experiment_name).experiment_id
  mlflow.set_experiment(experiment_name)
  def objective(trial):
    params={
        'learning_rate': trial.suggest_float("learning_rate", 0.001, 0.1, log=True),
        'n_estimators': trial.suggest_int("n_estimators", 50, 1000),
        'max_depth': trial.suggest_int("max_depth", 3, 10),
        'max_leaves': trial.suggest_int("max_leaves", 0, 100),
        'min_child_weight': trial.suggest_int("min_child_weight", 1, 5),
        'reg_alpha': trial.suggest_float("reg_alpha", 0.0, 1.0),
        'reg_lambda': trial.suggest_float("reg_lambda", 0.0, 1.0),
        'min_frequency': trial.suggest_float("min_frequency", 0.0, 1.0)
    }
    run_name = f"XGBoost_trial_{trial.number}"
    with mlflow.start_run(experiment_id=experiment_id):
        model= XGBClassifier(**params, use_label_encoder=False, eval_metric='logloss')
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        f1 = f1_score(y_test, y_pred)
        mlflow.log_params(params)
        mlflow.log_metric("valid_f1", f1)
        mlflow.xgboost.log_model(model, "model")
    return f1

  study = optuna.create_study(direction="maximize")
  study.optimize(objective, n_trials=10)

  os.makedirs("plots", exist_ok=True)
  with mlflow.start_run(experiment_id=experiment_id, run_name="Optimization_Plots"):
      fig1 = optuna.visualization.plot_optimization_history(study)
      fig1.write_image("plots/optimization_history.png")
      mlflow.log_artifact("plots/optimization_history.png")
      fig2 = optuna.visualization.plot_param_importances(study)
      fig2.write_image("plots/param_importances.png")
      mlflow.log_artifact("plots/param_importances.png")
  best_model=get_best_model(experiment_id)
  os.makedirs("models", exist_ok=True)

  with open("models/best_model.pkl", "wb") as f:
      pickle.dump(best_model, f)

  best_params = study.best_params
  with open('plots/best_model_config.txt', 'w') as f:
        f.write("Configuración del Mejor Modelo\n")
        f.write("="*50 + "\n")
        for param, value in best_params.items():
            f.write(f"{param}: {value}\n")
        f.write(f"\nMejor F1-score: {study.best_value}\n")
        plt.figure(figsize=(10, 6))
        xgb.plot_importance(best_model, max_num_features=10)
        plt.title('Importancia de Variables - Mejor Modelo XGBoost')
        plt.tight_layout()
        plt.savefig('plots/feature_importance.png', dpi=300, bbox_inches='tight')
        plt.close()
  with open('requirements.txt', 'w') as f:        
        f.write(f"pandas=={pd.__version__}\n")
        f.write(f"numpy=={np.__version__}\n")
        f.write(f"xgboost=={xgboost.__version__}\n")
        f.write(f"optuna=={optuna.__version__}\n")
        f.write(f"mlflow=={mlflow.__version__}\n")
        f.write(f"scikit-learn=={sklearn.__version__}\n")
        f.write(f"matplotlib=={matplotlib.__version__}\n")
        f.write("kaleido>=0.2.1\n")

  return best_model

In [ ]:
optimize_model()

[I 2025-10-21 15:11:36,404] A new study created in memory with name: no-name-f94af68f-3135-4a72-94af-81c2f80d2eed
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:11:36] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:11:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:11:36] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:11:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:11:41,149] Trial 0 finished with value: 0.463302752293578 and parameters: {'learning_rate': 0.049853165470068864, 'n_estimators': 289, 'max_depth': 9, 'max_leaves': 88, 'min_child_weight': 5, 'reg_alpha': 0.9354931882322289, 'reg_lambda': 0.21997758315704097, 'min_frequency': 0.925014356421363}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:11:41] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:11:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:11:41] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:11:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:11:46,385] Trial 1 finished with value: 0.4541284403669725 and parameters: {'learning_rate': 0.08492864368370628, 'n_estimators': 277, 'max_depth': 6, 'max_leaves': 45, 'min_child_weight': 5, 'reg_alpha': 0.12426580055207237, 'reg_lambda': 0.392137157472049, 'min_frequency': 0.11692447901073366}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:11:46] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:11:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:11:47] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:11:50 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:11:50,918] Trial 2 finished with value: 0.3668639053254438 and parameters: {'learning_rate': 0.005367810618333593, 'n_estimators': 336, 'max_depth': 9, 'max_leaves': 81, 'min_child_weight': 3, 'reg_alpha': 0.31847893190995724, 'reg_lambda': 0.5772815086284531, 'min_frequency': 0.6897694461342623}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:11:50] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:11:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:11:51] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:11:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:11:55,057] Trial 3 finished with value: 0.39452054794520547 and parameters: {'learning_rate': 0.04207734607490881, 'n_estimators': 187, 'max_depth': 10, 'max_leaves': 11, 'min_child_weight': 2, 'reg_alpha': 0.7583524604344279, 'reg_lambda': 0.8088713013514017, 'min_frequency': 0.2686182225277992}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:11:55] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:11:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:11:55] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:12:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:12:00,042] Trial 4 finished with value: 0.284789644012945 and parameters: {'learning_rate': 0.0011962300483157435, 'n_estimators': 909, 'max_depth': 4, 'max_leaves': 66, 'min_child_weight': 5, 'reg_alpha': 0.7175660161074172, 'reg_lambda': 0.39504891840238954, 'min_frequency': 0.7364037209770854}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:12:00] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:12:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:12:01] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:12:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:12:05,104] Trial 5 finished with value: 0.4387990762124711 and parameters: {'learning_rate': 0.08189177685195978, 'n_estimators': 977, 'max_depth': 5, 'max_leaves': 66, 'min_child_weight': 2, 'reg_alpha': 0.8200540360086637, 'reg_lambda': 0.8314335647743905, 'min_frequency': 0.8571659680385596}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:12:05] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:12:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:12:05] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:12:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:12:09,895] Trial 6 finished with value: 0.45410628019323673 and parameters: {'learning_rate': 0.025556066611752658, 'n_estimators': 848, 'max_depth': 4, 'max_leaves': 21, 'min_child_weight': 4, 'reg_alpha': 0.1617706189795336, 'reg_lambda': 0.03493223799205114, 'min_frequency': 0.36622257501738587}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:12:09] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:12:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:12:11] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:12:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:12:15,399] Trial 7 finished with value: 0.3018867924528302 and parameters: {'learning_rate': 0.0012693944504307867, 'n_estimators': 685, 'max_depth': 8, 'max_leaves': 80, 'min_child_weight': 2, 'reg_alpha': 0.2518264253758389, 'reg_lambda': 0.1569346460892863, 'min_frequency': 0.29696528865839167}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:12:15] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:12:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:12:17] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:12:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:12:21,669] Trial 8 finished with value: 0.43498817966903075 and parameters: {'learning_rate': 0.01658676570762544, 'n_estimators': 857, 'max_depth': 10, 'max_leaves': 81, 'min_child_weight': 1, 'reg_alpha': 0.4749698268535355, 'reg_lambda': 0.9893269077943848, 'min_frequency': 0.8145117096867756}. Best is trial 0 with value: 0.463302752293578.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\training.py:183: UserWarning: [15:12:21] WARNING: D:\bld\xgboost-split_1758007502304\work\src\learner.cc:738:
Parameters: { "min_frequency", "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
2025/10/21 15:12:22 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
c:\Users\naoca\.conda\envs\MDS7202_B\lib\site-packages\xgboost\sklearn.py:1028: UserWarning: [15:12:22] WARNING: D:\bld\xgboost-split_1758007502304\work\src\c_api\c_api.cc:1427: Saving model in the UBJSON format as default.  You can use file extension: `json`, `ubj` or `deprecated` to choose between formats.
  self.get_booster().save_model(fname)
2025/10/21 15:12:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2025-10-21 15:12:26,973] Trial 9 finished with value: 0.4409090909090909 and parameters: {'learning_rate': 0.06571857198107238, 'n_estimators': 872, 'max_depth': 8, 'max_leaves': 96, 'min_child_weight': 5, 'reg_alpha': 0.693998986470435, 'reg_lambda': 0.6283282065848135, 'min_frequency': 0.19551095446197686}. Best is trial 0 with value: 0.463302752293578.
C:\Users\naoca\AppData\Local\Temp\ipykernel_24760\1581425129.py:37: DeprecationWarning:


Support for Kaleido versions less than 1.0.0 is deprecated and will be removed after September 2025.
Please upgrade Kaleido to version 1.0.0 or greater (`pip install 'kaleido>=1.0.0'` or `pip install 'plotly[kaleido]'`).

# **2. FastAPI (2.0 puntos)**

<div align="center">
  <img src="https://media3.giphy.com/media/YQitE4YNQNahy/giphy-downsized-large.gif" width="500">
</div>

Con el modelo ya entrenado, la idea de esta sección es generar una API REST a la cual se le pueda hacer *requests* para así interactuar con su modelo. En particular, se le pide:

- Guardar el código de esta sección en el archivo `main.py`. Note que ejecutar `python main.py` debería levantar el servidor en el puerto por defecto.
- Defina `GET` con ruta tipo *home* que describa brevemente su modelo, el problema que intenta resolver, su entrada y salida.
- Defina un `POST` a la ruta `/potabilidad/` donde utilice su mejor optimizado para predecir si una medición de agua es o no potable. Por ejemplo, una llamada de esta ruta con un *body*:

```json
{
   "ph":10.316400384553162,
   "Hardness":217.2668424334475,
   "Solids":10676.508475429378,
   "Chloramines":3.445514571005745,
   "Sulfate":397.7549459751925,
   "Conductivity":492.20647361771086,
   "Organic_carbon":12.812732207582542,
   "Trihalomethanes":72.28192021570328,
   "Turbidity":3.4073494284238364
}
```

Su servidor debería retornar una respuesta HTML con código 200 con:


```json
{
  "potabilidad": 0 # respuesta puede variar según el clasificador que entrenen
}
```

**`HINT:` Recuerde que puede utilizar [http://localhost:8000/docs](http://localhost:8000/docs) para hacer un `POST`.**

# **3. Docker (2 puntos)**

<div align="center">
  <img src="https://miro.medium.com/v2/resize:fit:1400/1*9rafh2W0rbRJIKJzqYc8yA.gif" width="500">
</div>

Tras el éxito de su aplicación web para generar la salida, Smapina le solicita que genere un contenedor para poder ejecutarla en cualquier computador de la empresa de agua potable.

## **3.1 Creación de Container (1 punto)**

Cree un Dockerfile que use una imagen base de Python, copie los archivos del proyecto e instale las dependencias desde un `requirements.txt`. Con esto, construya y ejecute el contenedor Docker para la API configurada anteriormente. Entregue el código fuente (incluyendo `main.py`, `requirements.txt`, y `Dockerfile`) y la imagen Docker de la aplicación. Para la dockerización, asegúrese de cumplir con los siguientes puntos:

1. **Generar un archivo `.dockerignore`** que ignore carpetas y archivos innecesarios dentro del contenedor.
2. **Configurar un volumen** que permita la persistencia de los datos en una ruta local del computador.
3. **Exponer el puerto** para acceder a la ruta de la API sin tener que entrar al contenedor directamente.
4. **Incluir imágenes en el notebook** que muestren la ejecución del contenedor y los resultados obtenidos.
5. **Revisar y comentar los recursos utilizados por el contenedor**. Analice si los contenedores son livianos en términos de recursos.

## **3.2 Preguntas de Smapina (1 punto)**
Tras haber experimentado con Docker, Smapina desea profundizar más en el tema y decide realizarle las siguientes consultas:

- ¿Cómo se diferencia Docker de una máquina virtual (VM)?
- ¿Cuál es la diferencia entre usar Docker y ejecutar la aplicación directamente en el sistema local?
- ¿Cómo asegura Docker la consistencia entre diferentes entornos de desarrollo y producción?
- ¿Cómo se gestionan los volúmenes en Docker para la persistencia de datos?
- ¿Qué son Dockerfile y docker-compose.yml, y cuál es su propósito?

# Conclusión

Éxito!
<div align="center">
  <img src="https://i.pinimg.com/originals/55/f5/fd/55f5fdc9455989f8caf7fca7f93bd96a.gif" width="500">
</div>