# Laboratorio 5: Clasificación 🤗

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos - Primavera 2025</strong></center>

### Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### Equipo:

- Nombre de alumno 1: Naomí Cautivo B.
- Nombre de alumno 2: Máximo Flores Valenzuela

### **Link de repositorio de GitHub:** [maxfloresv/MDS7202](https://github.com/maxfloresv/MDS7202)

### Temas a tratar
- Clasificación en problemas desbalanceados
- Lightgbm y xgboost
- Pipelines

## Reglas:

- **Grupos de 2 personas**
- Fecha de entrega: Entregas Martes a las 23:59.
- Instrucciones del lab el viernes a las 16:15 en formato online. Asistencia no es obligatoria, pero se recomienda **fuertemente** asistir.
- <u>Prohibidas las copias</u>. Cualquier intento de copia será debidamente penalizado con el reglamento de la escuela.
- Tienen que subir el laboratorio a u-cursos y a su repositorio de github. Labs que no estén en u-cursos no serán revisados. Recuerden que el repositorio también tiene nota.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquier material del curso que estimen conveniente.



### Objetivos principales del laboratorio
- Comprender cómo trabajar con problemas de clasificación con clases desbalanceadas.
- Aplicar los modelos lightgbm y xgboost.
- Practicar Pipelines

# Parte Teórica [12 puntos]

1. Explique cuál es la diferencia entre los datos de entrenamiento y validación. [1 punto]

> **Respuesta**: Los datos de entrenamiento son los que se usan para que el modelo aprenda los parámetros que se ajustan mejor a los datos (p. ej., los coeficientes que acompañan a las variables independientes en una regresión), y los de validación se usan para poder ajustar los hiperparámetros que permiten refinar los resultados de los modelos (p. ej., el radio $\varepsilon$ y el número de muestras en DBSCAN).

2. Explique cuál es el principal desafío al trabajar problemas de clasificación con data no supervisada. [1 punto]

3. Explique en **sus palabras** qué es la matriz de confusión y para qué se utiliza. [1 puntos]

> **Respuesta**: La matriz de confusión tiene como fin mostrar las diferencias entre las predicciones de un modelo y sus respectivos valores reales en una tarea de clasificación. Se usa para evaluar el rendimiento de un modelo de aprendizaje supervisado. 

4. Escriba la fórmula de las siguientes métricas y explique con **sus palabras** cómo se interpretan. [1 punto cada uno]

  * Accuracy
  * Precision
  * Recall
  * F1 score

> **Respuesta**: Antes de definir las fórmulas, se necesitan definir los valores $\text{TP}$, $\text{TN}$ para los aciertos: verdaderos positivos y negativos respectivamente, y $\text{FP}$, $\text{FN}$ para los errores: falsos positivos y negativos respectivamente.
> $$
> \text{Accuracy} = \frac{\text{TP} + \text{TN}}{\text{TP} + \text{TN} + \text{FP} + \text{FN}};\, \text{Precision} = \frac{\text{TP}}{\text{TP} + \text{FP}};\, \text{Recall} = \frac{\text{TP}}{\text{TP} + \text{FN}};\, \\[1em] \text{F1-Score} = \frac{2\cdot \text{Precision} \cdot \text{Recall}}{\text{Precision} + \text{Recall}}
> $$
> Por un lado, $\text{Accuracy}$ mide la proporción de aciertos en las predicciones con respecto al total de clasificaciones, sin diferenciar entre positivas y negativas. Por otro lado, $\text{Precision}$ se enfoca específicamente en cuántas predicciones, de todas las que fueron clasificadas como positivas, se hicieron de manera correcta. Similarmente, $\text{Recall}$ realiza esto, pero con la proporción de ejemplos positivos capturados por el modelo con respecto al total de ejemplos positivos reales. Finalmente, $\text{F1-Score}$ es la media armónica entre $\text{Precision}$ y $\text{Recall}$. Esta media es parecida al promedio, salvo que penaliza mucho más cuando una de las dos métricas es menor, porque usa pesos inversamente proporcionales.

5. Explique qué métrica recomendaría para los siguientes contextos de clasificación. [1 punto cada uno]

  * Mantenimiento predictivo de fallas de maquinaria pesada en la industria minera.  
  > **Respuesta**: Maximizar $\text{Recall}$, porque es más grave decir que una máquina no falla cuando realmente sí fallaba ($\text{FN}$) por las consecuencias que eso puede traer en la industria minera, que al revés, donde se dice que la máquina falla, y en el mantenimiento se verá que realmente no tenía ningún problema, entonces se puede descartar.
  * Detección de enfermedades altamente contagiosas.
  > **Respuesta**: Maximizar $\text{Recall}$, porque es mucho más grave un falso negativo. Esto último corresponde a decirle a una persona que no está enferma, cuando realmente sí lo estaba, que podría incluso terminar en el fallecimiento del paciente, o una epidemia. Al revés ($\text{FP}$) puede tener efectos psicológicos, pero _a posteriori_ se puede reevaluar en el seguimiento médico, concluyendo que realmente el paciente no estaba enfermo.
  * Aprobación de créditos de alto riesgo.
  > **Respuesta**: Depende de la perspectiva por dónde se mire, pero en general, desde una visión empresarial, es mucho peor un falso positivo ($\text{FP}$), dado que estaría aprobándole el crédito a una persona que no es apta para poder pagarlo. En un falso negativo ($\text{FN}$), por lo menos el cliente se puede reevaluar con otra entidad que maneje este tipo de créditos. Así, maximizaría $\text{Precision}$.
  * Detección de crímenes.
  > **Respuesta**: Maximizar $\text{F1-Score}$, porque tanto un falso positivo como un falso negativo son graves. En el caso de un falso positivo porque estaríamos incriminando a alguien inocente, y en el caso de un falso negativo porque estaríamos dejando libre a un criminal.

6. Explique qué es la calibración de modelos y para qué se usa. [1 punto]
> **Respuesta**: La calibración de modelos se usa para mejorar el resultado de las predicciones en una tarea de aprendizaje supervisado. Requiere un nuevo conjunto de datos: el de calibración. Consiste en que la probabilidad de pertenencia a una clase en un problema -inicialmente binario, con extensión a multiclase- refleje efectivamente la estadística frecuentista que se puede calcular sobre dicha clase. Por ejemplo, si el modelo arroja que la probabilidad de ser de una clase $\mathcal{C}$ es de un $60 \%$, se espera que en los datos, la proporción de ejemplos de la clase $\mathcal{C}$ sea un porcentaje similar.

# Parte práctica [48 puntos]

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones.

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.

**Los Datos**

Para este laboratorio deberán trabajar con el csv `statsplayers.csv`, donde deberán aplicar algoritmos de aprendizaje supervisado de clasificación en base a características que describen de jugadores de fútbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [58]:
import pandas as pd

df_players = pd.read_csv('stats_players.csv')
df_players.head()

,Name,Nationality,National_Position,Club_Position,Height,Weight,Preffered_Foot,Age,Work_Rate,Weak_foot,...,Agility,Jumping,Heading,Shot_Power,Finishing,Long_Shots,Curve,Freekick_Accuracy,Penalties,Volleys
0,Cristiano Ronaldo,Portugal,LS,LW,185,80,Right,32,High / Low,4,...,90,95,85,92,93,90,81,76,85,88
1,Lionel Messi,Argentina,RW,RW,170,72,Left,29,Medium / Medium,4,...,90,68,71,85,95,88,89,90,74,85
2,Neymar,Brazil,LW,LW,174,68,Right,25,High / Medium,5,...,96,61,62,78,89,77,79,84,81,83
3,Luis Suárez,Uruguay,LS,ST,182,85,Right,30,High / Medium,4,...,86,69,77,87,94,86,86,84,85,88
4,Manuel Neuer,Germany,GK,GK,193,92,Right,31,Medium / Medium,4,...,52,78,25,25,13,16,14,11,47,11

## 1. Predicción de Seleccionados Nacionales [14 puntos]

<p align="center">
  <img src="https://www.futuro.cl/wp-content/uploads/2016/06/chile-argentina-meme-12.jpg" width="300">
</p>

### 1.1 Preprocesamiento [5 puntos]

Tareas:

1. Genere los labels para la clasificación binaria en una variable llamada `label`. Para esto, trabaje sobre el atributo `National_Position` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. [Sin puntaje]

2. Hecho esto, ¿cuántos se tienen ejemplos por cada clase? Comente lo que observa. [1 punto]

3. Genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guárdelo una variable llamada `col_transformer`. [2 puntos]

4. Comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material `Player_Stats_Report.html` que viene en el zip del lab), al igual que las transformaciones aplicadas. [2 puntos]

> **Respuesta:**

1. Genere los labels para la clasificación binaria en una variable llamada `label`. Para esto, trabaje sobre el atributo `National_Position` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país.

In [59]:
df_players['label'] = df_players['National_Position'].notna().astype(int)
df_players[['National_Position', 'label']].head(10)

  National_Position  label
0                LS      1
1                RW      1
2                LW      1
3                LS      1
4                GK      1
5                GK      1
6                LS      1
7                RS      1
8               NaN      0
9                GK      1

> 2. Hecho esto, ¿cuántos ejemplos se tienen por cada clase? Comente lo que observa.
>
> **Respuesta:** Mirando la distribución en la celda a continuación, se observa que hay $16.513$ ($\sim 93\text{,}89\, \%$) jugadores con la etiqueta $0$ (no seleccionados), y $1.075$ ($\sim 6\text{,}11\, \%$) con la etiqueta $1$ (seleccionados). Se observa un desbalance de clases.

In [60]:
df_players['label'].value_counts()

label
0    16513
1     1075
Name: count, dtype: int64

3. Genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guárdelo una variable llamada `col_transformer`.

In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (
  StandardScaler, 
  MinMaxScaler, 
  OneHotEncoder,
  OrdinalEncoder
)

std_columns = [
  'Height',
  'Weight',
  'Ball_Control',
  'Dribbling',
  'Aggression',
  'Reactions',
  'Vision',
  'Composure',
  'Short_Pass',
  'Long_Pass',
  'Acceleration',
  'Speed',
  'Stamina',
  'Strength',
  'Balance',
  'Agility',
  'Jumping',
  'Penalties'
]

minmax_columns = [
  'Age',
  'Marking',
  'Sliding_Tackle',
  'Standing_Tackle',
  'Interceptions',
  'Crossing',
  'Heading',
  'Shot_Power',
  'Finishing',
  'Long_Shots',
  'Curve',
  'Freekick_Accuracy',
  'Volleys'
]

onehot_columns = [
  'National_Position',
  'Club_Position',
  'Preffered_Foot',
  'Work_Rate'
]

ordenc_columns = [
  'Weak_foot',
  'Skill_Moves'
]

def create_column_transformer(
  std_columns=std_columns,
  minmax_columns=minmax_columns,
  onehot_columns=onehot_columns,
  ordenc_columns=ordenc_columns
) -> ColumnTransformer:
  """
  Create a column transformer for data preprocessing.

  Parameters
  ----------
  std_columns : list[str]
    List of columns to be standardized using StandardScaler.
  minmax_columns : list[str]
    List of columns to be scaled using MinMaxScaler.
  onehot_columns : list[str]
    List of columns to be one-hot encoded using OneHotEncoder.
  ordenc_columns : list[str]
    List of columns to be ordinally encoded using OrdinalEncoder.

  Returns
  -------
  ColumnTransformer
    A ColumnTransformer that applies the specified transformations to the respective columns.
  """
  ct = ColumnTransformer(
    transformers=[
      ('std_scaler', StandardScaler(), std_columns),
      ('minmax_scaler', MinMaxScaler(), minmax_columns),
      ('onehot_encoder', OneHotEncoder(drop='first', handle_unknown='ignore'), onehot_columns),
      ('ordinal_encoder', OrdinalEncoder(), ordenc_columns)
    ]
  )
  return ct

col_transformer = create_column_transformer()

4. Comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material `Player_Stats_Report.html` que viene en el zip del lab), al igual que las transformaciones aplicadas.
> **Respuesta**: Las transformaciones elegidas se separarán por el procesador utilizado para su justificación.
> - `StandardScaler`: Para variables numéricas que seguían una distribución similar a una normal.
> - `MinMaxScaler`: Para el resto de las variables numéricas que no seguían la distribución mencionada.
> - `OneHotEncoder`: Para variables categóricas que no seguían un orden. Se usó la opción `drop='first'` para evitar multicolinealidad perfecta, pues la suma de todas las variables de diseño dan exactamente $1$ en el caso de no eliminar alguna de estas variables.
> - `OrdinalEncoder`: Para el resto de variables categóricas, que sí seguían un orden (p. ej., una escala del $1$ al $5$ en el caso de `Skill_Moves`).

### 1.2 Entrenamiento [3 puntos]

Ahora, vamos a entrenar los pipelines generados en los pasos anteriores. Para esto, debe realizar las siguientes tareas:

1. Separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio). En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`). [1 puntos]


2. Defina un pipeline llamado `pipeline_xgboost` y otro llamado `pipeline_lightgbm`. Estos pipelines deben tener el mismo ColumnTransformer definido en la sección de preprocesamiento, pero deben variar los clasificadores de acuerdo al nombre de cada pipeline. [1 puntos]

3. Entrene los pipelines. [1 punto]

**Respuesta:**

1. Separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio). En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`).

> **Respuesta**: La proporción de separación será $70\, \%$ de entrenamiento y $30\, \%$ de prueba, dado que se poseen exactamente $17.588$ datos, lo que implicaría que el modelo aprenderá con $\sim 12.312$ de ellos; suficientes. Se usará la opción `stratify` sobre los _labels_ para mantener su distribución original.
>
> En particular, para las variables independientes, eliminamos las columnas `Name` y `Nationality`, dado que consideramos que no son relevantes en la predicción. Además, eliminamos `National_Position` porque es la variable de la cual se deduce el _label_: dejarla sería un problema de _data leakage_.

In [62]:
from sklearn.model_selection import train_test_split

X = df_players.drop(columns=['label', 'Name', 'Nationality', 'National_Position'])
y = df_players['label']

X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.3, random_state=42, stratify=y
)

2. Defina un pipeline llamado `pipeline_xgboost` y otro llamado `pipeline_lightgbm`. Estos pipelines deben tener el mismo ColumnTransformer definido en la sección de preprocesamiento, pero deben variar los clasificadores de acuerdo al nombre de cada pipeline.

In [63]:
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

col_transformer = create_column_transformer(
  onehot_columns=list(filter(lambda x: x != 'National_Position', onehot_columns))
)

pipeline_xgboost = Pipeline(steps=[
  ('preprocessor', col_transformer),
  ('classifier', XGBClassifier())
])

pipeline_lightgbm = Pipeline(steps=[
  ('preprocessor', col_transformer),
  ('classifier', LGBMClassifier(verbose=-1))
])

3. Entrene los pipelines.

In [64]:
pipeline_xgboost.fit(X_train, y_train)
pipeline_lightgbm.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('preprocessor',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('std_scaler',
                                                  StandardScaler(copy=True,
                                                                 with_mean=True,
                                                                 with_std=True),
                                                  ['Height', 'Weight',
                                                   'Ball_Control', 'Dribbling',
                                                   'Aggression', 'Reactions',
                                                   'Vision', 'Composure',
                                                   'Short_Pass', 'Long_Pass',
                                                   'Acceleration...
                 LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                colsample_bytree=1.0, importance_type='split',
                                learning_rate=0.1, max_depth=-1,
                                min_child_samples=20, min_child_weight=0.001,
                                min_split_gain=0.0, n_estimators=100,
                                n_jobs=None, num_leaves=31, objective=None,
                                random_state=None, reg_alpha=0.0,
                                reg_lambda=0.0, subsample=1.0,
                                subsample_for_bin=200000, subsample_freq=0,
                                verbose=-1))],
         verbose=False)

### 1.3 Resultados [6 puntos]

1. Calcule las métricas accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) para evaluar el rendimiento de los distintos modelos. Verifique sus resultados usando `classification_report`. [2 puntos]

2. Explique qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) y cómo influye la cantidad de ejemplos por clase en los resultados obtenidos. [2 puntos]

3. Explique qué métrica le parece más adecuada y concluya qué modelo tiene un mejor desempeño. [2 puntos]

**Respuesta:**

1. Calcule las métricas accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) para evaluar el rendimiento de los distintos modelos. Verifique sus resultados usando `classification_report`.

In [65]:
from sklearn.metrics import classification_report

y_pred_xgb = pipeline_xgboost.predict(X_test)
y_pred_lgbm = pipeline_lightgbm.predict(X_test)

print("XGBoost Classifier Report:\n")
print(classification_report(y_test, y_pred_xgb))

print("LightGBM Classifier Report:\n")
print(classification_report(y_test, y_pred_lgbm))

XGBoost Classifier Report:

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      4954
           1       0.53      0.14      0.22       323

    accuracy                           0.94      5277
   macro avg       0.74      0.57      0.60      5277
weighted avg       0.92      0.94      0.92      5277

LightGBM Classifier Report:

              precision    recall  f1-score   support

           0       0.95      0.99      0.97      4954
           1       0.52      0.13      0.21       323

    accuracy                           0.94      5277
   macro avg       0.73      0.56      0.59      5277
weighted avg       0.92      0.94      0.92      5277

2. Explique qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional) y cómo influye la cantidad de ejemplos por clase en los resultados obtenidos.

> **Respuesta**: Los valores de _precision_ y _recall_ para la clase positiva son $0\text{,}95$ y $0\text{,}99$, y el _accuracy_ es $0\text{,}94$. Esto quiere decir que el modelo clasificó correctamente el $94\, \%$ de los ejemplos totales, teniendo un mejor desempeño a la hora de minimizar los falsos negativos, pues su _recall_ es más cercano a $1$.
>
> La cantidad de ejemplos por clase influye directamente en los resultados obtenidos, dado que para la clase negativa, la clasificación es pésima: hay muchos ejemplos que son clasificados como «Seleccionados» y en realidad no eran jugadores seleccionados. Esto se refleja en el valor de _recall_, que es $0\text{,}14$ para XGBoost, y $0\text{,}13$ para LightGBM.

3. Explique qué métrica le parece más adecuada y concluya qué modelo tiene un mejor desempeño.

> **Respuesta:** Ambos errores, tanto los falsos positivos como negativos, son graves, considerando que el contexto es una selección de jugadores para una nómina (o análisis de mercado). Un falso positivo es grave, porque diría que un jugador es seleccionado nacional cuando no lo era, lo que cambia mucho la visión de negocio y el valor que el jugador puede tener. Ídem con un falso negativo, pero viceversa: digo que un jugador no es seleccionado nacional, cuando sí lo era. 
>
> Así, la métrica más adecuada para este caso es $\text{F1-Score}$, resultando en que XGBoost tiene un desempeño ligeramente mejor.

## 2. Predicción de posiciones de jugadores [4 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="300">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas.

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características.

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo `Club_Position`, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF']
central_ataque = ['RW', 'CAM', 'LW']
central = ['RM', 'CM', 'LM']
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

La elección del clasificador se justificar en base a la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y se deben comentar los resultados obtenidos en la clasificación.

**Tareas:** [1 punto por tarea]

1. En un nuevo dataframe, aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección y guárdelos en la variable `label`.
2. Cuente cuántos por clase quedan.
3. Entrene el nuevo pipeline y ejecute una evaluación de este.
4. Comente los resultados obtenidos.

**Respuesta:**

1. En un nuevo dataframe, aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección y guárdelos en la variable `label`.

> **Respuesta**: Lo más intuitivo es generar un diccionario donde cada posición está _mapeada_ a una etiqueta. Esa será la solución que se implementará.

In [66]:
attack = ['ST', 'CF']
central_attack = ['RW', 'CAM', 'LW']
central = ['RM', 'CM', 'LM']
central_defense = ['RWB', 'CDM', 'LWB']
defense = ['RB', 'CB', 'LB']
goalkeeper = ['GK']

position_map = {
  **dict.fromkeys(attack, "ataque"),
  **dict.fromkeys(central_attack, "central_ataque"),
  **dict.fromkeys(central, "central"),
  **dict.fromkeys(central_defense, "central_defensa"),
  **dict.fromkeys(defense, "defensa"),
  **dict.fromkeys(goalkeeper, "arquero"),
}

df_club_pos = df_players[
  df_players['Club_Position'].isin(position_map.keys())
].copy()

df_club_pos['label'] = df_club_pos['Club_Position'].map(position_map)
df_club_pos[['Club_Position', 'label']].head(10)

  Club_Position           label
0            LW  central_ataque
1            RW  central_ataque
2            LW  central_ataque
3            ST          ataque
4            GK         arquero
5            GK         arquero
6            ST          ataque
7            RW  central_ataque
8            ST          ataque
9            GK         arquero

2. Cuente cuántos por clase quedan.

> **Respuesta**: La etiqueta que más jugadores tiene asociados es `defensa`, con $1.180$, y la que menos tiene asociados es `central_defensa`, con $209$. Un conteo con más detalles se puede revisar en la tabla de la siguiente celda de código.

In [67]:
df_club_pos['label'].value_counts()

label
defensa            1180
central             907
arquero             632
central_ataque      581
ataque              430
central_defensa     209
Name: count, dtype: int64

3. Entrene el nuevo pipeline y ejecute una evaluación de este.

> **Respuesta**: Tal como en la sección anterior, se generará una partición tal que el $70\, \%$ de los datos queden en entrenamiento, y el restante $30\, \%$ para probar el rendimiento de los modelos, con estratificación. Acá, se eliminarán las mismas variables del ítem anterior, salvo `National_Position`, donde `Club_Position` toma su rol ahora. Las justificaciones son idénticas.
>
> En particular, usando la documentación proporcionada, se optó por usar el modelo `XGBoost` de la parte anterior, dado que es parte de los llamados _Ensemble Classifiers_, a los cuales se llega desde la tarea de clasificación, con el flujo para $<100\, \text{k}$ muestras.

In [68]:
from sklearn.preprocessing import LabelEncoder

X = df_club_pos.drop(columns=['label', 'Name', 'Nationality', 'Club_Position'])

le_club_pos = LabelEncoder()
y = le_club_pos.fit_transform(df_club_pos['label'])

X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.3, random_state=42, stratify=y
)

col_transformer = create_column_transformer(
  onehot_columns=list(filter(lambda x: x != 'Club_Position', onehot_columns))
)

pipeline_xgboost = Pipeline(steps=[
  ('preprocessor', col_transformer),
  ('classifier', XGBClassifier())
])

pipeline_xgboost.fit(X_train, y_train)
y_pred_xgb = pipeline_xgboost.predict(X_test)

print("XGBoost Classifier Report (Club Position):\n")
print(classification_report(y_test, y_pred_xgb))

XGBoost Classifier Report (Club Position):

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       190
           1       0.76      0.78      0.77       129
           2       0.54      0.58      0.56       272
           3       0.45      0.33      0.38       174
           4       0.41      0.19      0.26        63
           5       0.83      0.95      0.89       354

    accuracy                           0.72      1182
   macro avg       0.66      0.64      0.64      1182
weighted avg       0.70      0.72      0.71      1182

> donde las clases, en el orden que aparecen, son:

In [69]:
le_club_pos.classes_

array(['arquero', 'ataque', 'central', 'central_ataque',
       'central_defensa', 'defensa'], dtype=object)

4. Comente los resultados obtenidos.

> **Respuesta**: Las proporciones aproximadas de las clases en el _dataset_ original son: defensa ($30\, \%$), central ($23\, \%$), arquero ($16\, \%$), central_ataque ($14\text{,}7\, \%$), ataque ($10\text{,}9\, \%$) y central_defensa ($5\text{,}3\, \%$), cuyas etiquetas, en orden por el `LabelEncoder`, son: $[5, 2, 0, 3, 1, 4]$ (refiérase a la tabla de la siguiente celda de código). 
> 
> Con esto, podemos observar de inmediato que la clase peor clasificada, según la métrica $\text{F1-Score}$, es la que tiene menor proporción ($4$; central_defensa). La clase mejor clasificada según esta misma métrica es $0$; arquero. La segunda clase peor clasificada es $3$; central_ataque. Juntando toda esta información, podemos decir que el modelo tiene una alta confusión con la posición central, y no es capaz de clasificarla bien. En las clases que hacen referencia a dicha posición, hay muchos falsos negativos, dado lo bajo de la métrica _recall_.

In [70]:
df_club_pos_count = pd.DataFrame(df_club_pos['label'].value_counts())
df_club_pos_count['proportion'] = round(
  df_club_pos_count / df_club_pos_count.sum(),
  3
)

df_club_pos_count

                 count  proportion
label
defensa           1180       0.300
central            907       0.230
arquero            632       0.160
central_ataque     581       0.147
ataque             430       0.109
central_defensa    209       0.053

## 3. Predicciones de Seleccionados Nacionales para el Jere Klein [30 puntos]

<center>
<img src='https://www.radioactiva.cl/wp-content/uploads/2024/04/Jere-Klein-1-768x432.webp' width=500 />

Después de alcanzar la fama como cantante urbano, Jere Klein decide explorar una nueva faceta. Con su amor por el fútbol y convencido de que los artistas urbanos poseen un talento y versatilidad excepcionales, Jere se embarca en un proyecto innovador: desarrollar un sistema de inteligencia artificial capaz de identificar a jugadores que tienen potencial para convertirse en futbolistas profesionales. Su teoría es que muchos artistas del género urbano chileno, con sus habilidades únicas y su disciplina, podrían destacarse también en el deporte. Con este sistema, Jere espera no solo abrir nuevas oportunidades para sus colegas artistas, sino también demostrar la amplia gama de talentos que pueden ofrecer.

### 2.1 ¿Qué modelo de árbol es más de "pana"? [10 puntos]

<center>
<img src='https://64.media.tumblr.com/39189215a7d3d96823cb359f35b44e05/tumblr_psmrhrR3Xw1qf5hjqo4_540.gif' width=300 />


**Tareas**


1. Considerando el la variable llamada `label` creada en la sección 1.1. Para determinar cuál modelo de árbol sería más adecuado para la tarea en cuestión, utilice PyCaret. Este deberá centrarse exclusivamente en modelos de tipo árbol. Jere ha especificado que busca un modelo que tome decisiones rápidamente y que tenga una baja tasa de falsos positivos, ya que planea invertir en estos jugadores. [3 puntos]

Para la comparación, utilice los siguientes modelos:

```python
['et', 'rf', 'dt', 'xgboost', 'lightgbm', 'catboost']
```

2. Explique en brevemente que son los modelos de la siguiente lista `['et', 'rf', 'dt']` y como funcionan. [3 punto]

3. Tras realizar la comparación de modelos, seleccione aquel que muestre el mejor rendimiento en términos de velocidad y precisión, especialmente en la reducción de falsos positivos. Utilice la función `evaluate_model` de PyCaret para revisar y analizar los resultados obtenidos en los siguientes aspectos:

  - **Confusión Matrix**: ¿Cómo se encuentran la tasa de verdaderos positivos y verdaderos negativos?
  - **Threshold**: ¿Es acaso el umbral por defecto del modelo el mejor para las predicciones?
  - **Feature Importance**: ¿Cuáles son las variables con mejor desempeño? ¿A qué podría deberse esto?
  - **Learning Curve**: ¿El modelo presenta algún problema?

  [4 puntos]

> **Respuesta**:

1. Considerando la variable llamada `label` creada en la sección 1.1. Para determinar cuál modelo de árbol sería más adecuado para la tarea en cuestión, utilice PyCaret. Este deberá centrarse exclusivamente en modelos de tipo árbol. Jere ha especificado que busca un modelo que tome decisiones rápidamente y que tenga una baja tasa de falsos positivos, ya que planea invertir en estos jugadores.

> Considerando lo justificado en la sección 1.1, se eliminarán las variables `Name`, `Nationality` y `National_Position`. Es muy importante eliminar esta última para que los datos de entrenamiento y prueba no predigan con el patrón trivial revisando por la condición `notna()`.

In [ ]:
from pycaret.classification import *
import os
import gc
import time

os.environ["PYCARET_CUSTOM_LOGGING_LEVEL"] = "CRITICAL"

ct = create_column_transformer(
  onehot_columns=list(
    filter(
      lambda x: x != 'National_Position', onehot_columns
    )
  )
)

df = df_players.drop(columns=['National_Position', 'label'])
df = pd.DataFrame(
  ct.fit_transform(df), 
  columns=ct.get_feature_names_out()
)
df['label'] = df_players['label'].values

def train_evaluate_model(model_name: str) -> None:
  """
  Train and evaluate a tree classification model using PyCaret, optimizing Precision metric.
  If the tuned model already exists, the function won't retrain it.

  Parameters
  ----------
  model_name : str
    The name of the model to be trained. Supported models for this function are:
    'dt' (Decision Tree), 'rf' (Random Forest), 'et' (Extra Trees),
    'gbc' (Gradient Boosting Classifier), 'xgboost' (XGBoost),
    'lightgbm' (LightGBM) and 'catboost' (CatBoost).
  """
  if os.path.exists(f'models/tuned_{model_name}.pkl'):
    print(f"Model tuned_{model_name} already exists. Skipping training.")
    return
  
  clf = setup(
    data=df, 
    target='label',
    session_id=42,
    fold=5
  )

  start = time.time()
  if model_name == 'xgboost':
    model = create_model(
      model_name, 
      tree_method='gpu_hist', 
      predictor='gpu_predictor'
    )
  elif model_name == 'catboost':
    model = create_model(
      model_name, 
      task_type='GPU'
    )
  else:
    model = create_model(model_name)
  tuned_model = tune_model(model, n_iter=5, optimize='Precision')
  end = time.time()
  print(f"Training and tuning {model_name} took {end - start:.2f} seconds.")
  save_model(tuned_model, f'models/tuned_{model_name}')

  metrics = pull()
  metrics.to_excel(f"models/metrics/{model_name}.xlsx", index=False)

  del model, tuned_model, metrics, clf
  gc.collect()

model_list = [
  'dt', 
  'rf', 
  'et', 
  'xgboost', 
  'lightgbm', 
  'catboost'
]

for model in model_list:
  train_evaluate_model(model)

Model tuned_dt already exists. Skipping training.
Model tuned_rf already exists. Skipping training.
Model tuned_et already exists. Skipping training.
Model tuned_xgboost already exists. Skipping training.
Model tuned_lightgbm already exists. Skipping training.

Fitting 5 folds for each of 5 candidates, totalling 25 fits
Transformation Pipeline and Model Successfully Saved

### 2.2 Reducción de dimensionalidad [14 puntos]

<center>
<img src='https://i.kym-cdn.com/photos/images/original/002/258/560/668.gif' width=400 />

A pesar de los resultados obtenidos previamente, el manager de Jere ha solicitado el entrenamiento de un modelo de XGBoost utilizando los datos disponibles. Además, se debe proceder a realizar una reducción de dimensionalidad basada en la importancia de las características.

Para llevar a cabo esta tarea:

1. Inicie entrenando un modelo XGBoost con todas las características disponibles. [2 puntos]

2. Una vez el modelo esté entrenado, evalúe y clasifique las características según su importancia de forma descendente. [2 puntos]

3. Utilice esta clasificación para ejecutar una búsqueda recursiva de eliminación de características, eliminando progresivamente las menos importantes y evaluando el impacto en el desempeño del modelo hasta identificar las N características más críticas. [2 puntos]

4. Con este conjunto reducido de características, entrene un nuevo modelo y evalúe su rendimiento. [2 puntos]

5. Posteriormente, responda a las siguientes preguntas para una comprensión más profunda de los cambios y beneficios:

  - ¿El rendimiento del modelo con las características seleccionadas es similar al del modelo original? ¿Cómo se comparan en términos de precisión y robustez? [2 puntos]
  - ¿Cuáles son los beneficios potenciales de eliminar variables del modelo? Considere factores como la simplificación del modelo, reducción del tiempo de entrenamiento, y mejora en la capacidad de generalización. [2 puntos]
  - Comente si el modelo con menor dimensionalidad es más sencillo de explicar. Explique brevemente por qué la eliminación de ciertas características puede facilitar la comprensión y la explicación del comportamiento del modelo. [2 puntos]

Notar que con esta metodologia buscamos encontrar un punto entermedio entre número de festures y desempeño. por esto, si observa que al aumentar festires el aumento es despreciable, puede no considerar agregar más features a su modelo.

**Respuesta**

### 2.3 Calibración Probabilistica [6 puntos]

<center>
<img src='https://media2.giphy.com/media/l2Je4Ku0Cx292KWv6/200w.gif?cid=6c09b952y0sihtq9tb6sz8j2023x3zxxp3qx1ocgonkpkblj&ep=v1_gifs_search&rid=200w.gif&ct=g' width=400 />

Para lograr modelos más modulares, se recomienda realizar una calibración del modelo entrenado anteriormente, con el objetivo de obtener salidas que reflejen mayor modularidad.

1. Se solicita que utilice un método de calibración que asegure que las probabilidades generadas incrementen de manera monótona. Una métrica ampliamente utilizada para evaluar la precisión de la calibración de un modelo es el Brier Score. Calcule el Brier Score para el modelo tanto antes como después de la calibración. Esto le permitirá realizar una comparación cuantitativa y determinar si la calibración ha mejorado el rendimiento del modelo. Para más información sobre el Brier Score, puede consultar el siguiente enlace: [Scikit-Learn - Brier Score Loss](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.brier_score_loss.html). [3 puntos]

2. Tras la calibración, examine y comente los resultados obtenidos. A su análisis añada una comparación visual de las ideales versus las salidas del modelo original (sin calibrar) y del modelo calibrado. [3 puntos]

**Respuesta**

Mucho éxito!

<center>
<img src="https://i.pinimg.com/originals/55/3d/42/553d42bea9b10e0662a05aa8726fc7f4.gif" width=300>